# Data Preparation Code for NCAA Women's Basketball Dataset

# Step 1: Import Libraries

In [4]:
import pandas as pd

# Step 2: Load Datasets

In [5]:
rosters_df = pd.read_csv('/content/wbb_rosters_2022_23.csv', encoding='latin1')
teams_df = pd.read_csv('/content/teams.csv', encoding='latin1')

# Step 3: Merge Datasets to unify division data

In [6]:
merged_df = pd.merge(rosters_df, teams_df[['team', 'division']], on='team', how='left')
merged_df

,ncaa_id,team,player_id,name,year,hometown,homestate,high_school,previous_school_clean,height_clean,...,primary_position,secondary_position,position_clean,year_clean,redshirt,hs_clean,hometown_clean,state_clean,country_clean,division_y
0,721,Air Force,11807.0,Mackenzie Le,Freshman,Elk Grove,California,St. Francis,NaN,"5'3""",...,GUARD,NaN,GUARD,Freshman,0,St. Francis,"ELK GROVE, CA",CA,USA,I
1,721,Air Force,11805.0,Milahnie Perry,Freshman,Tampa,Florida,Seffner Christian Academy,NaN,"5'7""",...,GUARD,NaN,GUARD,Freshman,0,Seffner Christian Academy,"TAMPA, FL",FL,USA,I
2,721,Air Force,11801.0,Madison Smith,Sophomore,Connell,Washington,Connell,NaN,"5'8""",...,GUARD,NaN,GUARD,Sophomore,0,Connell,"CONNELL, WA",WA,USA,I
3,721,Air Force,11795.0,Taylor Britt,Junior,Columbia,South Carolina,Spring Valley,USAFA Prep,"5'7""",...,GUARD,NaN,GUARD,Junior,0,Spring Valley,"COLUMBIA, SC",SC,USA,I
4,721,Air Force,11796.0,Kamri Heath,Senior,Edmond,Oklahoma,Edmond North,NaN,"5'7""",...,GUARD,NaN,GUARD,Senior,0,Edmond North,"EDMOND, OK",OK,USA,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13801,985,Bluefield St.,1386.0,Derricka Bramwell,Redshirt Junior,Columbus,Ohio,Bishop Ready,NaN,"6'0""",...,CENTER,NaN,CENTER,Junior,1,Bishop Ready,"COLUMBUS, OH",OH,USA,II
13802,985,Bluefield St.,1387.0,Coraly Dupree,Redshirt Sophomore,Las Vegas,Nevada,Park University Gilbert,NaN,"6'1""",...,CENTER,NaN,CENTER,Sophomore,1,Park University Gilbert,"LAS VEGAS, NV",NV,USA,II
13803,985,Bluefield St.,1388.0,Gabrielle Thomas,Sophomore,Queensbury,New York,Queensbury,NaN,"5'10""",...,FORWARD,NaN,FORWARD,Sophomore,0,Queensbury,"QUEENSBURY, NY",NY,USA,II
13804,985,Bluefield St.,1390.0,Zaynah Robinson,Sophomore,Severn,Maryland,Fort Meade,NaN,"5'4""",...,GUARD,NaN,GUARD,Sophomore,0,Fort Meade,"SEVERN, MD",MD,USA,II
13805,985,Bluefield St.,1391.0,Dani Janutolo,Redshirt Senior,Bluefield,West Virginia,Tazewell,NaN,"5'10""",...,GUARD,NaN,GUARD,Senior,1,Tazewell,"BLUEFIELD, WV",WV,USA,II

# Step 4: Reduce Categories
# Group states with fewer than 50 players into 'Other'

In [7]:
state_counts = merged_df['state_clean'].value_counts()
states_to_keep = state_counts[state_counts >= 50].index
merged_df['state_grouped'] = merged_df['state_clean'].apply(lambda x: x if x in states_to_keep else 'Other')
merged_df

,ncaa_id,team,player_id,name,year,hometown,homestate,high_school,previous_school_clean,height_clean,...,secondary_position,position_clean,year_clean,redshirt,hs_clean,hometown_clean,state_clean,country_clean,division_y,state_grouped
0,721,Air Force,11807.0,Mackenzie Le,Freshman,Elk Grove,California,St. Francis,NaN,"5'3""",...,NaN,GUARD,Freshman,0,St. Francis,"ELK GROVE, CA",CA,USA,I,CA
1,721,Air Force,11805.0,Milahnie Perry,Freshman,Tampa,Florida,Seffner Christian Academy,NaN,"5'7""",...,NaN,GUARD,Freshman,0,Seffner Christian Academy,"TAMPA, FL",FL,USA,I,FL
2,721,Air Force,11801.0,Madison Smith,Sophomore,Connell,Washington,Connell,NaN,"5'8""",...,NaN,GUARD,Sophomore,0,Connell,"CONNELL, WA",WA,USA,I,WA
3,721,Air Force,11795.0,Taylor Britt,Junior,Columbia,South Carolina,Spring Valley,USAFA Prep,"5'7""",...,NaN,GUARD,Junior,0,Spring Valley,"COLUMBIA, SC",SC,USA,I,SC
4,721,Air Force,11796.0,Kamri Heath,Senior,Edmond,Oklahoma,Edmond North,NaN,"5'7""",...,NaN,GUARD,Senior,0,Edmond North,"EDMOND, OK",OK,USA,I,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13801,985,Bluefield St.,1386.0,Derricka Bramwell,Redshirt Junior,Columbus,Ohio,Bishop Ready,NaN,"6'0""",...,NaN,CENTER,Junior,1,Bishop Ready,"COLUMBUS, OH",OH,USA,II,OH
13802,985,Bluefield St.,1387.0,Coraly Dupree,Redshirt Sophomore,Las Vegas,Nevada,Park University Gilbert,NaN,"6'1""",...,NaN,CENTER,Sophomore,1,Park University Gilbert,"LAS VEGAS, NV",NV,USA,II,Other
13803,985,Bluefield St.,1388.0,Gabrielle Thomas,Sophomore,Queensbury,New York,Queensbury,NaN,"5'10""",...,NaN,FORWARD,Sophomore,0,Queensbury,"QUEENSBURY, NY",NY,USA,II,NY
13804,985,Bluefield St.,1390.0,Zaynah Robinson,Sophomore,Severn,Maryland,Fort Meade,NaN,"5'4""",...,NaN,GUARD,Sophomore,0,Fort Meade,"SEVERN, MD",MD,USA,II,MD
13805,985,Bluefield St.,1391.0,Dani Janutolo,Redshirt Senior,Bluefield,West Virginia,Tazewell,NaN,"5'10""",...,NaN,GUARD,Senior,1,Tazewell,"BLUEFIELD, WV",WV,USA,II,WV

# Group international players

In [8]:
merged_df['state_grouped'] = merged_df.apply(
    lambda row: 'International' if row['country_clean'] != 'USA' else row['state_grouped'], axis=1
)

# Simplify player positions

In [9]:
position_mapping = {'GUARD': 'Guard', 'FORWARD': 'Forward', 'CENTER': 'Center'}
merged_df['position_grouped'] = merged_df['primary_position'].map(position_mapping).fillna('Other')

# Step 5: Select Relevant Columns

In [10]:
final_df = merged_df[['division_y', 'year_clean', 'total_inches', 'state_grouped', 'position_grouped']].copy()
final_df.rename(columns={'division_y': 'division'}, inplace=True)

# Step 6: Clean Text Data

In [11]:
final_df['division'] = final_df['division'].str.strip()
final_df['year_clean'] = final_df['year_clean'].str.strip().str.lower()
final_df['state_grouped'] = final_df['state_grouped'].str.strip().str.lower()
final_df['position_grouped'] = final_df['position_grouped'].str.strip().str.lower()

# Step 7: Handle Missing Values

In [12]:
final_df = final_df.dropna()

# Optional export

In [13]:
final_df.to_csv('prepared_ncaa_wbb_data.csv', index=False)

# Verify results

In [14]:
print(final_df.head())

  division year_clean  total_inches state_grouped position_grouped
0        I   freshman          63.0            ca            guard
1        I   freshman          67.0            fl            guard
2        I  sophomore          68.0            wa            guard
3        I     junior          67.0            sc            guard
4        I     senior          67.0            ok            guard